### ISSUE TITLE
Tests fail on 1.9.3p0

### ISSUE THREAD

**Issue by jnicklas** [garybernhardt/raptor#17] opened 2011-11-10 07:43 UTC
I tried running the test suite, and I am getting a lot of failures. It works fine on 1.9.2 though. The failures seem to be related to includes in RSpec contexts, which are expected to pull in constants, but apparently don't on 1.9.3.

Here's a gist which illustrates the difference: https://gist.github.com/1354361

I have no idea why this is occuring. I will investigate further, just wanted to jot this down here.

**Comment by garybernhardt** [comment] 2011-11-19 21:07
I think that this is a bug between RSpec and 1.9.3: some constant lookup guts that RSpec relies on must have changed in 1.9.3. Let's defer until they look at it. I reported it here: https://github.com/rspec/rspec-core/issues/506

**Comment by garybernhardt** [comment] 2011-11-22 02:39
Reported as a bug in Ruby: http://redmine.ruby-lang.org/issues/5657

**Comment by garybernhardt** [comment] 2012-01-06 01:37
Tests were fixed by #22. This was caused by a bug in Ruby 1.9.2 that was fixed in 1.9.3. Raptor's tests were relying on the buggy behavior.

**Closed as completed by garybernhardt** 2012-01-06 01:37 UTC
